version: '3'
services:
  shopping-api:
    build: API/
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    depends_on:
      - sql-server
      - redis-server
    networks:
      - gateway_net

  sql-server:
    build: SQLServer/
    ports:
      - "1450:1433"
    volumes:
      - /var/lib/docker/volumes/mssqluser/_data:/var/opt/sqlserver
      - /var/lib/docker/volumes/mssqlsystem/_data:/var/opt/mssql
    networks:
      - gateway_net
  
  redis-server:
    image: "redis:6.0"
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    networks:
      - gateway_net
networks:
    gateway_net:
      external: true